trigger: ["master"]
pr: ["master"]

jobs:
# Check formatting
# - template: ci/azure-rustfmt.yml
#   parameters:
#     name: rustfmt

# Test top level crate
- template: ci/azure-test-stable.yml
  parameters:
    name: test_tokio
    displayName: Test tokio
    cross: true
