trigger: ["master"]
pr: ["master"]

jobs:
# Check formatting
# - template: ci/azure-rustfmt.yml
#   parameters:
#     name: rustfmt

# Test top level crate
- template: ci/azure-test-stable.yml
  parameters:
    name: test_tokio
    displayName: Test tokio
    cross: true

# This represents the minimum Rust version supported by
# Mio. Updating this should be done in a dedicated PR.
#
# Tests are not run as tests may require newer versions of
# rust.
- template: ci/azure-test-stable.yml
  parameters:
    name: minrust
    rust_version: 1.18.0
    cmd: check
    cross: true

# === Cross compilation ===

# iOS
- template: ci/azure-cross-compile.yml
  parameters:
    vmImage: macOS-10.13
    name: cross_ios
    displayName: Cross Compile iOS
    target: x86_64-apple-ios

# Android (ARM)
- template: ci/azure-cross-compile.yml
  parameters:
    name: cross_arm_android
    displayName: Cross Compile Android
    target: arm-linux-androideabi

# Android (ARM 64)
- template: ci/azure-cross-compile.yml
  parameters:
    name: cross_arm_android_64
    displayName: Cross Compile Android (64bit)
    target: aarch64-linux-android
