jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04

      ${{ if parameters.cross }}:
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: stable

  - template: azure-is-release.yml

  - script: cargo test
    env:
      CI: 'True'
    displayName: cargo test
    workingDirectory: $(Build.SourcesDirectory)/${{ crate }}
